BEGIN_VALUES = "qc" --file
ENDING_FLAGS = --language CS

AAttacker.cs: AAttacker.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

ARVRObjectEnableControl.cs: ARVRObjectEnableControl.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

Asteroid.cs: Asteroid.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

Constants.cs: Constants.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

CountryFlag.cs: CountryFlag.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

GameManager.cs: GameManager.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

GameOverScene.cs: GameOverScene.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

Missile.cs: Missile.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

MoveToVolumeAudio.cs: MoveToVolumeAudio.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

Planet.cs: Planet.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

Player.cs: Player.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

Prefabs.cs: Prefabs.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

Speaker.cs: Speaker.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

StartScene.cs: StartScene.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

WebCamDisplay.cs: WebCamDisplay.uqc
	$(BEGIN_VALUES) $< $(ENDING_FLAGS)

all: AAttacker.cs ARVRObjectEnableControl.cs Asteroid.cs Constants.cs CountryFlag.cs GameManager.cs GameOverScene.cs Missile.cs MoveToVolumeAudio.cs Planet.cs Player.cs Prefabs.cs Speaker.cs StartScene.cs WebCamDisplay.cs 
	echo "All done."

clean: 
	del AAttacker.cs ARVRObjectEnableControl.cs Asteroid.cs Constants.cs CountryFlag.cs GameManager.cs GameOverScene.cs Missile.cs MoveToVolumeAudio.cs Planet.cs Player.cs Prefabs.cs Speaker.cs StartScene.cs WebCamDisplay.cs 